apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevador-gramado-ix-deployment
  labels:
    app: elevador-gramado-ix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elevador-gramado-ix
  template:
    metadata:
      labels:
        app: elevador-gramado-ix
    spec:
      containers:
      - name: elevador-gramado-ix
        image: elevador-gramado-ix:latest  # Nome da imagem Docker
        imagePullPolicy: Never              # Garante que a imagem local será usada
        ports:
        - containerPort: 3000  # Porta interna no container onde a aplicação irá rodar
---
apiVersion: v1
kind: Service
metadata:
  name: elevador-gramado-ix-service
spec:
  type: NodePort  # Expor a aplicação externamente
  ports:
    - port: 3000        # Porta externa para acessar a aplicação
      targetPort: 3000  # Porta interna no container
      nodePort: 3000    # Porta do Node para acesso externo
  selector:
    app: elevador-gramado-ix
