apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevador-gramado-ix-deployment
  labels:
    app: elevador-gramado-ix
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: elevador-gramado-ix
  template:
    metadata:
      labels:
        app: elevador-gramado-ix
    spec:
      containers:
      - name: elevador-gramado-ix
        image: elevador-gramado-ix:latest 
        imagePullPolicy: Never             
        ports:
        - containerPort: 3000           
        resources:
          limits:
            memory: "512Mi"                
            cpu: "500m"                  
---
apiVersion: v1
kind: Service
metadata:
  name: elevador-gramado-ix-service
spec:
  type: NodePort  
  ports:
    - port: 3000       
      targetPort: 3000 
      nodePort: 30001   
  selector:
    app: elevador-gramado-ix  
