name: Deploy to Kubernetes (Servidor)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar ao Servidor e Fazer Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Definir diretório do projeto
            cd /home/usuario/projetos/tela-elevador-gramado

            # Atualizar código do repositório
            git pull origin master

            # Construir a imagem Docker no próprio servidor
            docker build -t tela-elevador-gramado:latest .

            # Remover pods antigos do Kubernetes para atualizar a versão
            kubectl delete deployment tela-elevador-gramado --ignore-not-found

            # Aplicar o deployment no Kubernetes
            kubectl apply -f /home/usuario/k8s/tela-elevador-gramado-deployment.yaml
