name: Deploy to Kubernetes (Servidor)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar ao Servidor e Fazer Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tela-elevador-gramado
            git pull origin master
            docker build -t tela-elevador-gramado:latest .
            kubectl delete deployment tela-elevador-gramado --ignore-not-found
            kubectl apply -f ~/k8s/tela-elevador-gramado-deployment.yaml
