name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master  # Disparar o pipeline quando houver push na branch 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy code to server
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        rsync -avz --exclude '.git' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/root/elevador-gramado-ix

    - name: Build and deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/root/elevador-gramado-ix
        docker build -t elevador-gramado-ix:latest .
        kubectl set image deployment/elevador-gramado-ix-deployment elevador-gramado-ix=elevador-gramado-ix:latest
        EOF
